# Site settings
title: Salar Bahador Resume
name: Salar Bahador

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/SaliBhdr
 - title: StackOverflow
   url: https://stackoverflow.com/users/8031400/salar-bahador?tab=profile
 - title: LinkedIn
   url: https://www.linkedin.com/in/salar-bahador
 - title: Farsi Resume
   url: https://salibhdr.github.io/resumeFa/

#Any buzzword skills you want to include
skills:
  - PHP
  - Laravel
  - Yii
  - Mysql
  - Mongodb
  - Python
  - Javascript
  - Jquery
  - API Design
  - REST
  - Git
  - Dart
  - Flutter
  - VueJs
  - SQL

#Work experience is required
roles:
  - title: Senior Backend Developer
    start: 2018
    end: Ongoing
    employer: TGBS Co.
    description: Developing Rest API for Winigames mobile application - Mobile game application ( Available on google play, cafe bazaar, Iran Apps), Developing Digital marketing and ads web-based software - VAS, Building 100% percent of An audiobook app named Kholase ( Available on google play, cafe bazaar, Iran Apps), Developing and maintaining Value-added service application
  - title: Senior Backend Developer
    start: 2018
    end: 2018
    employer: Sarir Rayaneh Gostar
    description: Building domain parking website along with API Building automation CRM, Contributing to building a search engine Building Word stemmer, Building word to excel converter Building excel to word converter
  - title: Web developer
    start: 2016
    end: 2018
    employer: Ibulud
    description: Developing Websites
  - title: Web developer
    start: 2015
    end: 2016
    employer: Arsham
    description: Developing Websites

#Education is required
education:
  - level: Master
    date: 2019
    subject: Software engineering
    school: University of PNU Tehran North
  - level: Bachelor
    date: 2010
    subject: Software engineering
    school: University of Urmia

#List of interesting Github repo/projects to include - optional
github:
 - SaliBhdr/typhoon-iran-cities
 - SaliBhdr/typhoon-rate
 - SaliBhdr/typhoon-cache
 - SaliBhdr/typhoon-url-signer
 - SaliBhdr/typhoon_flutter_clock
 - SaliBhdr/typhoon-telegram
 - SaliBhdr/flutter-calculator
 - SaliBhdr/social-share
 - SaliBhdr/typhoon-secure-file
 - SaliBhdr/tower-of-hanoi-php

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/8031400/salar-bahador
   flairimageurl: https://stackoverflow.com/users/flair/8031400.png

intro: |
  I'm PHP developer <br/>
  I'm a Laravel specialist<br/>
  I focus on creating clean and complicated websites<br/>
  I host websites<br/>
  I build mobile application with flutter for android and IOS<br/>
  I build API services and microservices Experience<br/>
  Resume Assesment link : <a href="https://github.com/SaliBhdr/PNU_3991_AR/blob/main/_General/SB_GeneralSection_CheckList_AR_3991.pdf" target="_blank">Click Me!!!</a><br>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Experience</strong>: In August 2015, I started working at a top dental management agency called Dentonic where I worked as a full-time PHP developer for 8 months.But, looking to improve my skills to the next level I had to make the hard decision to leave Dentonic and look for a new opportunity. In September 2017 I joined 'ibulud', another web agency which uses Laravel as a daily tool/framework.And besides that, I started moving to a part-time freelancer part-time employee schedule. I quickly had more demand than time available for new projects.I've been working on various projects as a freelancer, on small to big teams.In September 2018 I started to work with sarir computer but it didn't last long and after to month in November 2018 I started to work with TGBSCo a web and mobile application agency. I in part of three main products of this company winigames, digital marketing, and kholase audiobooks.<br/><br/>
